secret_key_base: <%= SecureRandom.hex(64) %>
active_record_encryption:
  primary_key: <%= SecureRandom.hex(32) %>
  deterministic_key: <%= SecureRandom.hex(32) %>
  key_derivation_salt: <%= SecureRandom.hex(32) %> 